#!/bin/bash

# Update HOST with actual value, uniquely generated by Docker on each start
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/listener.ora
sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" $ORACLE_HOME/network/admin/tnsnames.ora
/usr/sbin/sshd -D
echo "••• `date` - Apache vai iniciar "
# exec apache2  -DFOREGROUND
exec apache2
echo "••• `date` - Oracle XE vai iniciar "
while true; do
    pmon=`ps -ef | grep pmon_$ORACLE_SID | grep -v grep`

    if [ "$pmon" == "" ]
    then
        date
        /etc/init.d/oracle-xe start
    fi
    sleep 1m
done;
echo "Verifique o nome do HOST no listener.ora e tnsnames.ora"
grep HOST $ORACLE_HOME/network/admin/listener.ora
grep HOST $ORACLE_HOME/network/admin/tnsnames.ora

sleep 10
echo "••• `date` - Tomcat 8 vai iniciar "
${CATALINA_HOME}/bin/catalina.sh run
